TEAMS = {
    "South": {
        "1": "North Carolina",
        "2": "Kentucky",
        "3": "UCLA",
        "4": "Butler",
        "5": "Minnesota",
        "6": "Cincinnati",
        "7": "Dayton",
        "8": "Arkansas",
        "9": "Seton Hall",
        "10": "Wichita St.",
        "11": "Kansas St. or Wake Forest",
        "12": "Middle Tennessee",
        "13": "Winthrop",
        "14": "Kent St.",
        "15": "Northern Kentucky",
        "16": "Texas Southern"
    },
    "West": {
        "1": "Gonzaga",
        "2": "Arizona",
        "3": "Florida St.",
        "4": "West Virginia",
        "5": "Notre Dame",
        "6": "Maryland",
        "7": "Saint Mary's",
        "8": "Northwestern",
        "9": "Vanderbilt",
        "10": "VCU",
        "11": "Xavier",
        "12": "Princeton",
        "13": "Bucknell",
        "14": "Florida Gulf Coast U",
        "15": "North Dakota",
        "16": "South Dakota St."
    },
    "East": {
        "1": "Villanova",
        "2": "Duke",
        "3": "Baylor",
        "4": "Florida",
        "5": "Virginia",
        "6": "SMU",
        "7": "South Carolina",
        "8": "Wisconsin",
        "9": "Virginia Tech",
        "10": "Marquette",
        "11": "Providence or USC",
        "12": "UNCW",
        "13": "Eastern Tennessee St.",
        "14": "New Mexico St.",
        "15": "Troy",
        "16": "MSM/NO"
    },
    "Midwest": {
        "1": "Kansas",
        "2": "Louisville",
        "3": "Oregon",
        "4": "Purdue",
        "5": "Iowa St.",
        "6": "Creighton",
        "7": "Michgan",
        "8": "Miami U",
        "9": "Michigan St.",
        "10": "Oklahoma St.",
        "11": "Rhode Island",
        "12": "Nevada",
        "13": "Vermont",
        "14": "Iona",
        "15": "Jacksonville St.",
        "16": "NCC/UCD"
    }
}
